# Generated by Django 3.1.3 on 2020-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20201122_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
    ]
