# Generated by Django 3.1.3 on 2020-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default='text tag', verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
