# Generated by Django 3.1.3 on 2020-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='post.Tag', verbose_name='Теги'),
        ),
    ]
