# Generated by Django 3.1.3 on 2020-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20201123_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='post.Tag', verbose_name='Теги'),
        ),
    ]
