# Generated by Django 3.1.3 on 2020-11-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20201123_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='/static/python.png/', upload_to='images/'),
        ),
    ]
