# Generated by Django 3.1.3 on 2020-11-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='/static/python_WpUXF2U.png/', upload_to='images/'),
        ),
    ]
