# Generated by Django 3.1.3 on 2020-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20201125_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='/static/python_WpUXF2U.png/', height_field=100, upload_to='images/', width_field=100),
        ),
    ]
