# Generated by Django 3.1.3 on 2020-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20201125_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='/static/python_WpUXF2U.png/', upload_to=''),
        ),
    ]
