# Generated by Django 3.1.3 on 2020-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20201125_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='/static/python.png/', upload_to='images/'),
        ),
    ]
