# Generated by Django 3.1.3 on 2020-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20201125_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='/static/images/python.png/', upload_to='images/'),
        ),
    ]
