# Generated by Django 3.1.3 on 2020-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20201125_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.Tag', verbose_name='Теги'),
        ),
    ]
