# Generated by Django 3.1.3 on 2020-11-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
