# Generated by Django 3.1.3 on 2020-12-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_basket_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='product_count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
