# Generated by Django 3.1.3 on 2020-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productinbasket_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.TextField(choices=[(1, 'Обработка заказа'), (2, 'Доставка'), (3, 'Получен')], max_length=30)),
                ('products', models.ManyToManyField(to='shop.Product')),
            ],
        ),
    ]
